[project]
name = "codegen-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain[agents]>=1.0.3",
    "langchain-anthropic>=1.0.1",
    "pydantic>=2.12.3",
]
